version: '3.8'

services:
  crdt-host:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    image: crdt-host

  crdt-host-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    image: crdt-host-dev
    profiles:
      - dev

